### ISSUE TITLE
Locale restriction to German

### ISSUE THREAD

**Issue by nuss** [inpsyde/Akismet-Privacy-Policies#2]
Hello,

I've recently installed the "Akismet Privacy Policy" plugin on a blog of a client of mine. That blog is hosted in Germany and the company running it is also situated in Germany. However, the blog is held in English. Only switching the blog's locale to German made the plugin work. However, not only the backend is now translated to German but also some phrases in the publicly visible pages and posts. This is certainly not ideal.
My question: Why is this locale restriction imposed at all? As in my case not every wordpress installation hosted in Germany is necessarily held in German. German legislation though applies to these as well. Wouldn't it be enough to simply inform blog admins that the plugin is meant for installations run on German servers? (Aside from that: Isn't the DSGVO/GDPR EU-wide legislation? Doesn't the problem exist in other EU member states exist as well? IANAL...).

Tanks for your attention!

**Comment by bueltge** [comment]
The plugin was created for the German user group in focus. However you can change the content for the front end inside the back end, the settings page of the plugin, see https://github.com/inpsyde/Akismet-Privacy-Policies/blob/master/assets/screenshot-2.png
So maybe it should right you add your information content and done?

**Comment by nuss** [comment]
Thanks for the info. Yes, I already knew that and it's just what I did. However, one has to set the blog's locale to German to make the Alismet opt-in work which will consequently translate e.g. the phrase "Leave a Reply" to "Schreibe einen Kommentar" (regardless of what you've translated the plugin's info text to). 
For now I've simply commented out the locale restriction in the constructor of plugin's `Akismet_Privacy_Policies` class. I think that's exactly what I'd like it to be like. Only translating the info text in the plugin's settings is not sufficient. Of course I would have to do this again any time the plugin gets updated...

**Comment by bueltge** [comment]
Hi @nuss 
Thanks for the explained comment. Maybe you will send a Pull Request to improve this from your change? I will check it and maybe it will merge to the source and release a new version so that all users get a benefit from your change. Thanks.

**Comment by nuss** [comment]
pull request is here: #5

**Comment by bueltge** [comment]
Hi @nuss 
Please would you test the current branch https://github.com/inpsyde/Akismet-Privacy-Policies/tree/multilanguage_pr5
Thanks for your help!

**Comment by nuss** [comment]
@bueltge - Thanks very much! I've just checked out your branch and so far everything seems to works as expected.

**Comment by bueltge** [comment]
Great, fast Feedback! I'm currently not on my priority client, But I will check that I add the SVN of w.org to release a new version also on this client.
