### ISSUE TITLE
500 Error when visitors try to comment.

### ISSUE THREAD

**Issue by AMcGrady** [inpsyde/Akismet-Privacy-Policies#3]
On site fetzionista.at users are unable to leave comments while Akismet Privacy Policies plugin is active. Users trying to comment receive 500 Internal Server Error. I've disabled the plugin for now but the user would like to be able to use it.

**Comment by bueltge** [comment]
Can you try with a active WP_DEBUG? I mean the plugin don't change this, it add only a hint to the comments and no rewrite that have the possibility to fail in a 500.

**Comment by AMcGrady** [comment]
Site is hosted through WordPress.com. Any recommendations for a compatible debug plugin to do this?
