### ISSUE TITLE
[multilanguage_pr5] changes to settings are not picked up if page is cached by WP Super Cache (possibly happening with other caching plugins as well)

### ISSUE THREAD

**Issue by nuss** [inpsyde/Akismet-Privacy-Policies#7]
In a page that I'm currently working on I found the following pecularity: On that page I'm using WP Super Cache to speed up page loading. Normally, if I e.g. change the content of some page, changes are picked up even though the has been cached (I don't really know about the internals of WP Super Cache). However this is not the case for updated settings in Akismet-Privacy-Policies - I first have to clear the cache of WP Super Cache. Then the notice is displayed as set in the backend.
It's not really a big issue if you have understood the reason behind that behaviour but I guess it might cause some confusion for people who don't know. I don't know how to fix this flaw resp. how to create a generalized solution that would work with all caching plaugins out there. Possibly it would be good (and sufficient) to add a short notice to the plugin's README.

What do you think?

**Comment by bueltge** [comment]
But this is a expected behavior. Caching plugins store each content, so you should exclude this content if the cache plugins have an option for this. We should not change the logic of caching via plugin in our workspace.
